### ISSUE TITLE
Getting wrong History Database file when there are multiple user profiles in Chrome/Chromium.

### ISSUE THREAD

**Issue by ghost** [MyOutDeskLLC/node-browser-history#14]
When a user has multiple user profiles in Chrome, there are separate folders for the profiles other than the "Default" Folder. Both the "Default" folder and the user profile folder (e.g. "Profile 1") has separate history file. So the regex gets the first History file inside the "Default" folder which is wrong in case of the user using the "Profile 1". 

So, in that case the returned history array is always empty.

**Comment by rmchale** [comment]
Does it make sense to to export `getBrowserHistory` so a caller could override the default paths?

**Comment by mohit-mamtora** [comment]
this will solve multiple profile issue #21
