### ISSUE TITLE
using node-browser-history in eletron

### ISSUE THREAD

**Issue by alaysd** [MyOutDeskLLC/node-browser-history#3]
placing getAllHistroy() method inside setInterval does not give latest history. It loads the browser data once and keeps showing the same data. Any ideas ? Thanks in advance

**Comment by tance77** [comment]
I'll look into this. Haven't tested it inside an interval before. 

Calling ```getAllHistory()``` with no params defaults to the last 5 minutes.

**Comment by tance77** [comment]
Fixed here https://github.com/MyOutDeskLLC/node-browser-history/commit/9c6795ae9b095bd0cc599c6ae91911183b97f613

**Comment by alaysd** [comment]
Thanks a lot mate ??
