### ISSUE TITLE
Too many dependencies, can't find packages

### ISSUE THREAD

**Issue by James-Baloyi** [MyOutDeskLLC/node-browser-history#5]
can't find modules that are clearly there
![screenshot 2019-02-06 at 10 31 10](https://user-images.githubusercontent.com/25753980/52329101-73085700-29fa-11e9-9afd-4883f03e7cb3.png)

**Comment by tance77** [comment]
This should be fixed in https://github.com/MyOutDeskLLC/node-browser-history/pull/10 Most of the dependencies were removed and I opted for an async sqlite wrapper
